# Generated by Django 4.2.7 on 2025-10-09 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('sport_type', models.CharField(choices=[('бокс', 'Бокс'), ('кикбоксинг', 'Кикбоксинг'), ('муай-тай', 'Муай-тай'), ('BJJ', 'BJJ'), ('вольная борьба', 'Вольная борьба'), ('тхэквондо', 'Тхэквондо'), ('ОФП', 'ОФП')], max_length=20, verbose_name='Вид спорта')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
