# Generated by Django 4.2.7 on 2025-10-09 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('hero', 'Главная секция (Hero)'), ('lot1', 'Лот 1'), ('lot2', 'Лот 2'), ('lot3', 'Лот 3'), ('about', 'Секция "Об аукционе"'), ('training', 'Секция "Тренировки"'), ('logo', 'Логотип'), ('background', 'Фоновое изображение')], max_length=20, verbose_name='Компонент')),
                ('image_url', models.URLField(verbose_name='Ссылка на изображение')),
                ('alt_text', models.CharField(max_length=200, verbose_name='Альтернативный текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Изображение компонента',
                'verbose_name_plural': 'Изображения компонентов',
                'ordering': ['component', '-created_at'],
            },
        ),
    ]
